// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTIkVpzbVl2NNfsn7hJXALPoW-_OZTMDM',
    appId: '1:628689087514:web:f217b11cffcdaec992f5a3',
    messagingSenderId: '628689087514',
    projectId: 'car-rental-app-93526',
    authDomain: 'car-rental-app-93526.firebaseapp.com',
    databaseURL: 'https://car-rental-app-93526-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-app-93526.firebasestorage.app',
    measurementId: 'G-1PEKKMSNPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBToyzN7iDzZe17qY8E4KSpkLId-YSuI',
    appId: '1:628689087514:android:7c3f2860a0398b6c92f5a3',
    messagingSenderId: '628689087514',
    projectId: 'car-rental-app-93526',
    databaseURL: 'https://car-rental-app-93526-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-app-93526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJXEeW4zvSErK9AlKwkdyNGqoOF7no7Qc',
    appId: '1:628689087514:ios:f91b9d751f66defb92f5a3',
    messagingSenderId: '628689087514',
    projectId: 'car-rental-app-93526',
    databaseURL: 'https://car-rental-app-93526-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-app-93526.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJXEeW4zvSErK9AlKwkdyNGqoOF7no7Qc',
    appId: '1:628689087514:ios:f91b9d751f66defb92f5a3',
    messagingSenderId: '628689087514',
    projectId: 'car-rental-app-93526',
    databaseURL: 'https://car-rental-app-93526-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-app-93526.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTIkVpzbVl2NNfsn7hJXALPoW-_OZTMDM',
    appId: '1:628689087514:web:09a759a43c4ad32392f5a3',
    messagingSenderId: '628689087514',
    projectId: 'car-rental-app-93526',
    authDomain: 'car-rental-app-93526.firebaseapp.com',
    databaseURL: 'https://car-rental-app-93526-default-rtdb.firebaseio.com',
    storageBucket: 'car-rental-app-93526.firebasestorage.app',
    measurementId: 'G-F5LV007DVK',
  );
}
